tagbase/tagbase-server

openapi.yaml
=> ISSUE-8 Upgrade openapi specification to 3.0.3

.github/dependabot.yml
=> ISSUE-9  Establish Dependabot for automating dependency-related pull requests

README.md, docker-compose.yml, openapi.yaml, services/postgres/Dockerfile, tagbase_server/requirements.txt, tagbase_server/tagbase_server/__main__.py, tagbase_server/tagbase_server/controllers/ingest_controller.py, tagbase_server/tagbase_server/openapi/openapi.yaml, tagbase_server/test-requirements.txt
=> ISSUE-11 Upgrade to PostgreSQL 14

services/pgadmin4/Dockerfile
=> ISSUE-36 Upgrade pgadmin4 service to 6.5

tagbase_server/requirements.txt, tagbase_server/setup.py, tagbase_server/tagbase_server/__main__.py
This issue addresses #45 as mentioned before I selected Tornado as the production server.
=> ISSUE-45 Switch to a production web server

.github/workflows/build.yml
=> ISSUE-54 Add 'sonar.python.version' flag to sonarcloud.io analysis

.github/workflows/build.yml, openapi.yaml, tagbase-server-openapi-rules.yaml, tagbase_server/tagbase_server/controllers/ingest_controller.py, tagbase_server/tagbase_server/openapi/openapi.yaml, tagbase_server/tagbase_server/test/test_ingest_controller.py
=> ISSUE-43 Augment OpenAPI spec with a netCDF ingestion capability

services/pgadmin4/Dockerfile
=> ISSUE-68 Upgrade to pgAdmin 6.7

.gitignore, docker-compose.yml, tagbase_server/tagbase_server/controllers/ingest_controller.py
=> ISSUE-79 Implement host-based persistent disk storage for the PostgreSQL service

openapi.yaml, tagbase_server/tagbase_server/controllers/ingest_controller.py
Addresses #78 a following ticket will deliver the Python implementation for this API.
=> ISSUE-78 Augment OpenAPI with /tag path

services/postgres/Dockerfile, services/postgres/sqldb/tagbase_schema_20220430.sql, tagbase_server/tagbase_server/controllers/ingest_controller.py, tagbase_server/tox.ini
PR gets past the recurring issues
* https://github.com/tagbase/tagbase-server/issues/81
* https://github.com/tagbase/tagbase-server/issues/83
* https://github.com/tagbase/tagbase-server/issues/84
This PR DOES NOT fix ingestion for the above names files so more work is still needed before #99 is closed.
=> ISSUE-99 Implement new schema updates to tagbase-schema.sql to accomodate multiple position dataset solutions per tag deployment

services/postgres/sqldb/tagbase_schema_20220430.sql, tagbase_server/tagbase_server/utils/processing_utils.py
PR addresses #115 
This PR also fixes a bug in processing of global attributes.
=> ISSUE-115 Simplify data_migration TRIGGER logic

ingest_controller.py, openapi.yaml, services/pgadmin4/Dockerfile, services/postgres/sqldb/tagbase_schema_20220430.sql, tagbase_server/.openapi-generator/FILES, tagbase_server/README.md, tagbase_server/tagbase_server/__main__.py, tagbase_server/tagbase_server/controllers/tags_controller.py, tagbase_server/tagbase_server/models/__init__.py, tagbase_server/tagbase_server/models/tag200_tag_inner.py, tagbase_server/tagbase_server/openapi/openapi.yaml, tagbase_server/tagbase_server/test/test_tags_controller.py, tagbase_server/tagbase_server/util.py, tagbase_server/tagbase_server/utils/processing_utils.py, tags_controller.py
WIP for #118 I need to perform more local testing.
=> ISSUE-118 Replace submission.version with submission.solution_id and ensure solution_id is populated through data_position and metadata_position

.gitignore, README.md, docker-compose.yml
=> ISSUE-128 Augment tagbase_server docker composition to add a volume claim for log duplication

.github/workflows/build.yml
Attempt to supersede https://github.com/tagbase/tagbase-server/pull/109
=> Supersede https://github.com/tagbase/tagbase-server/pull/109

.github/workflows/build.yml
Reverts tagbase/tagbase-server#130
=> Revert "Supersede https://github.com/tagbase/tagbase-server/pull/109"

openapi.yaml, services/nginx/config/nginx.conf, services/nginx/proxy/index.html, tagbase_server/tagbase_server/controllers/ingest_controller.py, tagbase_server/tagbase_server/openapi/openapi.yaml, tagbase_server/tagbase_server/utils/io_utils.py
WIP towards `POST /ingest`. Given the new logic implemented via NGINX, I need to figure out the logic for acquiring rhe filename from the POST request. Once I get the filename I can check whether data should be processed as text or decompressed. _connection_ documentation is very limited so I will work towards this one.
=> WIP ISSUE-66 Implement POST logic for /ingest path

docker-compose.yml
=> ISSUE-176 Upgrade to pgAdmin4:latest

.github/workflows/build.yml, tagbase_server/setup.py, tagbase_server/tox.ini
=> ISSUE-183 Augment unit testing, tox and CI to cover Python 3.11

docker-compose.yml, services/docker-cron/Dockerfile, services/fswatch/Dockerfile, services/fswatch/post.sh
Addresses #189 
This one is pretty straightforward @renato2099 but there were also a few gotchas which I can explain when we review this.
=> ISSUE-189 Implement a filesystem watch to enable automated ingestion

services/fswatch/post.sh
=> 194: Specify fswatch events

tagbase_server/MANIFEST.in, tagbase_server/setup.py
=> ISSUE-200 Address duplicate tagbase_server dependecy declarations

docker-compose.yml
Addresses https://github.com/tagbase/tagbase-server/issues/195
@renato2099 take a look at https://github.com/kartoza/docker-postgis/issues/412
=> ISSUE-195 Prevent tagbase_schema.sql from being bootstapped on every PostGIS container startup

services/fswatch/post.sh
Supersedes #213 and addresses #211
=> ISSUE-211 fswatch needs to account for empty files created by sftp clients

services/fswatch/post.sh
@lewismc  there is still an issue with the post.sh script. Please checkout the fix in this PR
=> Fixes #215

services/postgis/tagbase_materialized_views.sql
=> ISSUE-220 data_position.lon needs to be cast to double in tagbase_materialized_views.sql

tagbase_server/tagbase_server/utils/processing_utils.py
Addresses #224 
@renato2099 I retained the logging but changed it to `debug` mode.
=> ISSUE-224 metadata.tag_id incorrectly mimics metadata.submission_id

openapi.yaml, tagbase_server/tagbase_server/models/error_container.py, tagbase_server/tagbase_server/openapi/openapi.yaml
=> ISSUE-254 ErrorContainer schema minItems needs to be greater than 0 in openapi.yaml

tagbase_server/tagbase_server/test/test_ingest.py, tagbase_server/tagbase_server/utils/processing_utils.py
Reverts tagbase/tagbase-server#241
=> Revert "240: Fix issue 240 avoid loading entire observation file"

services/postgis/tagbase_schema.sql, tagbase_server/tagbase_server/test/test_ingest.py, tagbase_server/tagbase_server/utils/io_utils.py, tagbase_server/tagbase_server/utils/processing_utils.py
=> ISSUE-239 Implement signature calculation for each file
